# Generated by Django 5.2.9 on 2025-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_firm_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='advisor_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Advisor ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firm_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Firm/Company Name'),
        ),
    ]
